
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ["functions", "deploy", "inference", "--gen2", "--region=asia-east1", "--source=.", "--trigger-http", "--runtime=python311", "--memory=8GB", "--cpu=8", "--env-vars-file=env.yaml", --timeout=600]
